### ISSUE TITLE
Please add a screen shot and a license file

### ISSUE THREAD

**Issue by unixorn** [Raniconduh/zshfish#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Raniconduh** [comment]
Solved - I've added an image to the readme and have added the license file. Thanks for taking interest in my theme!
